### ISSUE TITLE
chore: project setting

### ISSUE THREAD

**Issue by JSK0406** [softeerbootcamp4th/Team1-Strawberry-FE#1]
### 설명
프로젝트 초기 설정 및 git 설정

### todo
- [x] eslint 설치하기
- [x] prettier 설정하기
- [x] styled component 설치하기
- [x] pr template 설정하기
- [x] issue template 설정하기
- [x] label 설정하기
- [x] css 기본 설정 리셋
- [x] 간략한 폴더 구조 추가
